add localized string feature add open file function for cache folder
Bigfoot71/raymob pull request #19
Opened 2024-09-20 12:11 UTC by GreenSnakeLinux

add localized string feature
add open file function for cache folder

2024-09-20 20:25 UTC, Bigfoot71 requested changes
This PR seems to propose useful additions; thank you very much for this contribution!

A few adjustments are necessary, and overall, I think all these additions can be simplified into just two C functions: `LoadCacheFile` _(for example)_ and `GetL10NString` directly in `helper.c`.

Please read the comments for more information. If you have any feedback on mine, feel free to share!

Thanks again for your contribution!

2024-09-20 20:25 UTC, Bigfoot71 commented on app/src/main/cpp/deps/raymob/features.c
There are several issues with `getL10NString`. The first is that it should not return an empty string in case of failure, since a valid result should be freed from memory afterward. It would be more appropriate to return `NULL` on failure.

Secondly, the Java method should be integrated directly into `NativeLoader`, as `Features` is more suited for optional features that can be toggled through `gradle.properties`. Furthermore, this feature requires extending the `Features` class, while it could be added to `NativeLoader` without such modifications.

Additionally, it is entirely possible to write a _plain_ C version without needing to call a custom intermediary Java method. Here is an example that could be directly integrated into `helper.c`, with its declaration in `raymob.h`, without needing to modify `Features.java` or `NativeLoader.java`:

```c
char* GetL10NString(const char* value)
{
    jobject nativeInstance = GetNativeLoaderInstance();

    if (nativeInstance != NULL)
    {
        JNIEnv* env = AttachCurrentThread();

        // Get the native context class (nativeInstance)
        jclass nativeClass = (*env)->GetObjectClass(env, nativeInstance);

        // Get the native instance's getResources method
        jmethodID getResourcesMethod = (*env)->GetMethodID(env, nativeClass, "getResources", "()Landroid/content/res/Resources;");
        jobject resources = (*env)->CallObjectMethod(env, nativeInstance, getResourcesMethod);

        // Get the getIdentifier method of the Resources class
        jclass resourcesClass = (*env)->GetObjectClass(env, resources);
        jmethodID getIdentifierMethod = (*env)->GetMethodID(env, resourcesClass, "getIdentifier",
                                                            "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I");

        // Convert string name passed as parameter to jstring
        jstring resourceName = (*env)->NewStringUTF(env, value);
        jstring defType = (*env)->NewStringUTF(env, "string");

        // Get the package name of the native instance
        jmethodID getPackageNameMethod = (*env)->GetMethodID(env, nativeClass, "getPackageName", "()Ljava/lang/String;");
        jstring packageName = (jstring)(*env)->CallObjectMethod(env, nativeInstance, getPackageNameMethod);

        // Call getIdentifier to get the resource identifier
        jint resId = (*env)->CallIntMethod(env, resources, getIdentifierMethod, resourceName, defType, packageName);

        // Clean up used local references
        (*env)->DeleteLocalRef(env, resourceName);
        (*env)->DeleteLocalRef(env, defType);

        if (resId == 0) {
            // No identifier found for this resource
            DetachCurrentThread();
            return NULL;
        }

        // Call getString with the obtained identifier
        jmethodID getStringMethod = (*env)->GetMethodID(env, nativeClass, "getString", "(I)Ljava/lang/String;");
        jstring rv = (jstring)(*env)->CallObjectMethod(env, nativeInstance, getStringMethod, resId);

        if (rv == NULL) {
            DetachCurrentThread();
            return NULL;
        }

        // Convert jstring to char*
        const char* strReturn = (*env)->GetStringUTFChars(env, rv, NULL);

        // Allocate memory for returned string
        size_t len = strlen(strReturn) + 1;
        char* stringValue = malloc(len);

        if (stringValue) {
            strncpy(stringValue, strReturn, len);
            stringValue[len - 1] = '\0'; // Sécurité : terminer par '\0'
        }

        // Free UTF string and clean local references
        (*env)->ReleaseStringUTFChars(env, rv, strReturn);
        (*env)->DeleteLocalRef(env, rv);

        DetachCurrentThread();
        return stringValue;
    }

    return NULL;
}
```

2024-09-20 20:25 UTC, Bigfoot71 commented on app/src/main/java/com/raylib/raymob/Features.java
See my comment for `features.c`, these modifications are not necessary and the function can also be moved directly to `helper.c`

2024-09-20 20:53 UTC, GreenSnakeLinux commented
Awesome, all those adjustment are great and simpler

2024-10-06 16:24 UTC, Bigfoot71 commented
@GreenSnakeLinux I hope you're doing well. I wanted to check if you were planning to make the suggested changes from the review, so I can validate them and accept your contribution?

2024-10-20 15:47 UTC, GreenSnakeLinux commented
@Bigfoot71 did you received a notification about my update ?

2024-10-20 17:12 UTC, Bigfoot71 commented
> @Bigfoot71 did you received a notification about my update ?

I just saw this, I'm quite busy, I'll merge this evening (at home), there will be a few adjustments to make.
Thanks again!

2024-10-21 11:55 UTC, Bigfoot71 approved these changes

2024-10-21 11:55 UTC, merged